name: Build Mac Application
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Build with PyInstaller
        run: pyinstaller --onefile --windowed datacreate.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-application
          path: dist/datacreate.app
